### ISSUE TITLE
Minor typos in user guide

### ISSUE THREAD

**Issue by SQ77** [Vshnv2001/eff-bi#201]
![Screenshot 2024-11-13 194059](https://github.com/user-attachments/assets/dc680dec-dd1e-44ee-a00f-4cd4d17568db)
Getting started > Table Permissions
Should `when the sign up` be `when they sign up` instead?

![Screenshot 2024-11-13 194117](https://github.com/user-attachments/assets/fb9b2564-ee1e-4782-91b8-c346b6e6c05c)
FAQ > What happens if I make changes to my original database?
Should `tables that are delete` be `tables that are deleted` instead?

**Comment by bryanhce** [comment]
@SQ77 Thank you for pointing these mistakes out! We have pushed the update.
